# Generated by Django 6.0 on 2026-01-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0004_remove_category_slug_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('sale', 'Sale'), ('sold', 'Sold')], max_length=10, null=True),
        ),
    ]
