# Generated by Django 6.0 on 2026-01-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0009_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('sale', 'Sale'), ('sold_out', 'Sold Out'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
