# Generated by Django 6.0 on 2026-01-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0010_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('sale', 'Sale'), ('sold_out', 'Sold Out')], default='normal', max_length=20),
        ),
    ]
