# Generated by Django 6.0 on 2026-01-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0011_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('sale', 'Sale'), ('sold_out', 'Sold Out')], max_length=20, null=True),
        ),
    ]
