# Generated by Django 6.0 on 2026-01-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0012_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
