# Generated by Django 6.0 on 2026-01-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0013_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('new', 'New'), ('sale', 'Sale'), ('sold_out', 'Sold Out')], max_length=20, null=True),
        ),
    ]
