# Generated by Django 6.0 on 2026-01-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaizen_app', '0014_alter_product_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
